// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class AtualizarFuncionarioTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void atualizarFuncionario() {
    driver.get("http://localhost/Funcionarios/dashBoardFuncionario.html");
    driver.manage().window().setSize(new Dimension(1382, 754));
    {
      List<WebElement> elements = driver.findElements(By.id("func"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.id("func")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("tr:nth-child(2) > button:nth-child(4)"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("tr:nth-child(2) > button:nth-child(5)"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.cssSelector("tr:nth-child(2) > button:nth-child(4)")).click();
    {
      List<WebElement> elements = driver.findElements(By.id("nome-campo"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.id("email-campo"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.id("funcao-campo"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.id("post-btn")).click();
    driver.findElement(By.id("nome-campo")).click();
    driver.findElement(By.id("nome-campo")).sendKeys("Joao Paulo Silva");
    driver.findElement(By.id("email-campo")).sendKeys("JoaoPauloSilva@email.com");
    driver.findElement(By.id("funcao-campo")).click();
    driver.findElement(By.id("funcao-campo")).sendKeys("Programador");
    driver.findElement(By.id("post-btn")).click();
    driver.findElement(By.id("func")).click();
  }
}
