// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class AtualizarServicoTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void atualizarServico() {
    driver.get("http://localhost/Servicos/dashBoard.html");
    driver.manage().window().setSize(new Dimension(1382, 754));
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".botoes-lateral:nth-child(5)"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".botoes-lateral:nth-child(7)"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.cssSelector(".botoes-lateral:nth-child(7)")).click();
    driver.findElement(By.cssSelector(".botoes-lateral:nth-child(5)")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".botoes-lateral:nth-child(5)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("#table > tr:nth-child(2) > button:nth-child(3)"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("tr:nth-child(2) > button:nth-child(4)"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.cssSelector("#table > tr:nth-child(2) > button:nth-child(3)")).click();
    {
      List<WebElement> elements = driver.findElements(By.id("prego"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.id("tijolo"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.id("cimento"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.id("caixa-texto"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".botao-centro"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.cssSelector(".botao-centro")).click();
    driver.findElement(By.id("prego")).click();
    driver.findElement(By.id("prego")).sendKeys("1");
    driver.findElement(By.id("tijolo")).click();
    driver.findElement(By.id("tijolo")).sendKeys("1");
    driver.findElement(By.id("cimento")).click();
    driver.findElement(By.id("cimento")).sendKeys("1");
    driver.findElement(By.id("caixa-texto")).click();
    driver.findElement(By.id("caixa-texto")).sendKeys("Servico de Joao Pé de Feijão");
    driver.findElement(By.cssSelector(".botao-centro")).click();
  }
}
